language: objective-c

osx_image: xcode8.2

script:
   travis_retry xcodebuild -project ModelingFormChanges-Example.xcodeproj -scheme ModelingFormChanges-Example test -destination "platform=iOS Simulator,OS=10.1,name=iPhone SE"
