language: objective-c

osx_image: xcode8

script:
   xcodebuild -project ModelingFormChanges-Example.xcodeproj -scheme ModelingFormChanges-Example test -destination 'platform=iOS Simulator,name=iPhone 6'
